### ISSUE TITLE
Error 522 when trying to downlaod

### ISSUE THREAD

**Issue by Mladenrs** [qgis/QGIS-Website#469] opened 2024-11-09 11:38 UTC
### URL

https://download.qgis.org//downloads/macos/qgis-macos-pr.dmg

### On what type of device(s) did you see this bug?

Desktop

### On which operating system(s) are you seeing the problem?

MacOs

### On which browser(s) are you seeing the problem?

Chrome

### Summary

![Screenshot 2024-11-09 at 12 37 44](https://github.com/user-attachments/assets/944cad40-27dd-4690-aa95-03abd8092440)

**Comment by cvueghs1971** [comment] 2024-11-09 14:29
Hi we're having the same problems here, Windows 10 platform, coming from Belgium
Windows Edge browser
Desktop
![image](https://github.com/user-attachments/assets/31a6d49e-17bc-48b0-8e11-36738f615bc3)

**Comment by rubenalbur** [comment] 2024-11-09 15:06
hi! same problem from Spain on windows 11

**Comment by jef-n** [comment] 2024-11-09 19:17
duplicate of #470

**Closed as completed by jef-n** 2024-11-09 19:17 UTC
