### ISSUE TITLE
error 522 to download mac version

### ISSUE THREAD

**Issue by Tenertine** [qgis/QGIS-Website#468] opened 2024-11-09 09:45 UTC
### On what type of device(s) did you see this bug?

Desktop

### On which operating system(s) are you seeing the problem?

MacOs

### Other Browser

Opera

### Summary

![Opera Instantané_2024-11-09_164351_download qgis org](https://github.com/user-attachments/assets/17d10421-e10b-429d-8371-2282aaffa92c)

**Comment by paulrollings** [comment] 2024-11-09 18:41
Yes I have the same issue.

**Comment by jef-n** [comment] 2024-11-09 19:17
duplicate of #470

**Closed by jef-n** 2024-11-09 19:17 UTC
